-- CREATE USER (connected as SYSTEM user)

CREATE USER ORDER_USER IDENTIFIED BY order;
GRANT CREATE SESSION TO ORDER_USER;
GRANT CREATE TABLE TO ORDER_USER;
GRANT CREATE SEQUENCE TO ORDER_USER;
ALTER DATABASE DEFAULT TABLESPACE users;
GRANT UNLIMITED TABLESPACE TO ORDER_USER;